name: Go

on: ["push", "pull_request"]

jobs:

  build_and_test:
    name: "Run tests and build artifacts"
    strategy:
      matrix:
        os: ["ubuntu-latest", "macOS-latest"]
        go: ["1.15.x"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v1
      name: "Install Golang"
      with:
        go-version: ${{ matrix.go }}
    
    - uses: actions/checkout@v2
    
    - name: "Test"
      run: |
        cd katzenmint
        make

    - name: "Build"
      run: |
        make build
        mkdir dist
        mv katzenmint dist

    - if: runner.os == 'macOS'
      name: "Setup filename"
      run: echo "ZIPNAME=katzenmint_darwin" >> $GITHUB_ENV

    - if: runner.os == 'Linux'
      name: "Setup filename"
      run: echo "ZIPNAME=katzenmint_linux" >> $GITHUB_ENV

    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ZIPNAME }}
        path: dist
